# workflow for snake in my readme Github
name:  Snake Game - Readme Github

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animations
      - name: Generate GitHub Contributions Snake Animations

        uses: Platane/snk@v3
        with:
            # github user name to read the contribution graph from (**required**)
            # using action context var `github.repository_owner` or specified user
            github_user_name: ${{ github.repository_owner }}

            # list of files to generate.
            # one file per line. Each output can be customized with options as query string.
            #
            #  supported options:
            #  - palette:     A preset of color, one of [github, github-dark, github-light]
            #  - color_snake: Color of the snake
            #  - color_dots:  Coma separated list of dots color.
            #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
            #                 Exactly 5 colors are expected.
            outputs: |
                dist/github-snake.svg
                dist/github-snake-dark.svg?palette=github-dark
                dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Deploy the generated files to the 'output' branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          # Optionally, you can set a custom commit message
          commit_message: "Update snake animation [skip ci]"
